classification/apps/main/urls.py
from django.conf.urls import include, url
from .views import IndexView


urlpatterns = [
    url(r'^$',
        IndexView.as_view(),
        name='index'),
]

classification/apps/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^vetting/',
        include('sourcevetting.urls', namespace='sourcevetting')),

    #url(r'^obslog/',
    #            include('obslog.urls', namespace='obslog')),
    
    url(r'^',
        include('classification.apps.main.urls', namespace='main')),
]

classification/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from markdownx import urls as markdownx


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include(markdownx)),
    url(r'^accounts/', include('classification.account_urls')),
    url(r'^', include('classification.apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classification/apps/main/models.py
from django.db import models

# Create your models here.

classification/apps/main/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'main/index.html'

classification/apps/main/templates/main/base.html
{% extends "base.html" %}

classification/apps/main/templates/main/index.html
{% extends "main/base.html" %}

classification/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Classification</title>
{% block stylesheets %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" media="screen and (max-width: 640px)" href="{% static 'css/small.css' %}" />
{% endblock stylesheets %}
{% block scripts %}{% endblock scripts %}
{% endblock head %}</head>
<body>
{% block user %}{% include "user.html" %}{% endblock user %}
<nav>{% block nav %}{% include "nav.html" %}{% endblock nav %}</nav>
{% block content %}
{% endblock content %}
{% block footer %}{% include "footer.html" %}{% endblock footer %}
</body>
</html>

classification/templates/footer.html
<div id="footer"></div>

classification/templates/nav.html
<a href="{% url 'main:index' %}">home</a><a href="{% url 'sourcevetting:index' %}">vetting</a><a href="{# url 'obslog:index' #}">obslog</a>

classification/templates/profile.html
{% extends "base.html" %}
{% block content %}
<ul>	
	<li><a href="{% url 'logout' %}">Log out</a></li>
	<li><a href="{% url 'password_change' %}">Change password</a></li>
</ul>
{% endblock content %}

classification/templates/user.html
{% if user.is_authenticated %}<nav class="user"><a href="{% url 'login' %}">{{ user.username }}</a><a href="{% url 'logout' %}">Log out</a></nav>{% endif %}